artifact_uri: /home/snoronha/projects/instruction_tuning_olmo/mlflow_results/olmo_orcaslim_instruct/990176035551730847/31bdf2c3c41d41cf9ae1595be67d753b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '990176035551730847'
lifecycle_stage: active
run_id: 31bdf2c3c41d41cf9ae1595be67d753b
run_name: intelligent-eel-228
run_uuid: 31bdf2c3c41d41cf9ae1595be67d753b
source_name: ''
source_type: 4
source_version: ''
start_time: 1712782357525
status: 1
tags: []
user_id: snoronha
